### PR TITLE
ReceipeSearch

### PR DESCRIPTION
**Pull request by Harnoorsinghdhothar**

### CODE REVIEW

**Review by KPM007 — COMMENTED** [review]
ok

**Review by Yashkaran-Singh — COMMENTED** [review]
done

**Review by Davinder2501 — COMMENTED** [review]
okay

**Review by Yashkaran-Singh — APPROVED** [review]
GOOD WORK

**Review by Davinder2501 — APPROVED** [review]
okay

**Review by KPM007 — APPROVED** [review]
ok

**Review by Yashkaran-Singh — APPROVED** [review]

**Comment by Yashkaran-Singh** [comment]
GOODD

**Pull request closed without merging**
